[project]
name = "dds_project"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    { name = "Виктор Сагалаков", email = "sagalakov.viktor@gmail.com" },
]
dependencies = ["django>=5.2.7",
    "drf-spectacular>=0.28.0",
    "djangorestframework>=3.16.1",
    "django-filter>=25.1",
    "django-autocomplete-light>=3.12.1",
    "django-environ>=0.12.0"]
requires-python = ">=3.13"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[dependency-groups]
dev = [
    "black>=25.9.0",
    "isort>=7.0.0",
    "pytest>=8.4.2",
    "pytest-django>=4.11.1",
    "pytest-asyncio>=1.2.0",
    "factory-boy>=3.3.3",
    "faker>=37.11.0",
    "httpx>=0.28.1",
    "django-environ>=0.12.0
]
